services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'SPRING_AI_OPEN_AI_API_KEY'


    ports:
      - '27017'
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
